#!/usr/bin/env bash
## This file is not meant to be executed directly.
## It should be executed via a symlink, named the same as the executable you wish to execute inside the Docker image.

## Documentation at https://github.com/hugojosefson/node-via-docker-wrapper#readme

# Fail on any error
set -e

# Configurable env variables
NODE_VERSION="${NODE_VERSION:-lts}"
DOCKER_IMAGE="${DOCKER_IMAGE:-node:${NODE_VERSION}}"

DOCKER_USER=${DOCKER_USER:-"$(id -u)":"$(id -g)"}
DOCKER_WORKDIR="${DOCKER_WORKDIR:-$(pwd)}"
DOCKER_WORKDIR="$(cd ${DOCKER_WORKDIR} && pwd)"
DOCKER_EXTRA_ARGS="${DOCKER_EXTRA_ARGS:-}"
DOCKER_EXECUTABLE="${DOCKER_EXECUTABLE:-$(basename "${0}")}"
DOCKER_CACHE_BASE="${DOCKER_CACHE_BASE:-${HOME}/.cache/node-via-docker}"
DOCKER_CACHE_IDENTIFIER="${DOCKER_CACHE_IDENTIFIER:-${DOCKER_WORKDIR}}"
DOCKER_CACHE="${DOCKER_CACHE:-${DOCKER_CACHE_BASE}${DOCKER_CACHE_IDENTIFIER}}"

# Numeric booleans, for legibility
true=0
false=1

# Are we in a TTY?
function isTTY() {
  if [[ -t 1 ]]; then
    return ${true}
  else
    return ${false}
  fi
}

# Is current directory a git repository?
function isGitRepo() {
  if [[ -d .git ]]; then
    return ${true}
  else
    return ${false}
  fi
}

# Write current git user config to local repo, so it is visible inside the Docker container.
function writeGitUserToConfig() {
  gitEmail="$(git config user.email)"
  gitName="$(git config user.name)"
  git config --unset-all user.email
  git config --unset-all user.name
  git config --add user.email "${gitEmail}"
  git config --add user.name "${gitName}"
}

# Program starts here
if isTTY; then
  TTY_ARG="--tty"
else
  TTY_ARG=""
fi

if isGitRepo; then
  writeGitUserToConfig
fi

if [[ ! -z "${PORT}" ]]; then
  PORT_ARGS="--env PORT=${PORT} --publish ${PORT}:${PORT}"
else
  PORT_ARGS=""
fi

mkdir -p "${DOCKER_CACHE}/home"

docker run \
  --rm \
  --interactive \
  ${TTY_ARG} \
  --user ${DOCKER_USER} \
  --workdir "${DOCKER_WORKDIR}" \
  --volume "${DOCKER_WORKDIR}":"${DOCKER_WORKDIR}" \
  --volume "${DOCKER_CACHE}/home":"${HOME}" \
  --env HOME="${HOME}" \
  ${PORT_ARGS} \
  ${DOCKER_EXTRA_ARGS} \
  ${DOCKER_IMAGE} \
  ${DOCKER_EXECUTABLE} "$@"
